// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/sigpatsearch.h"
#include <Rcpp.h>

using namespace Rcpp;

// lib_new_search_e
SEXP lib_new_search_e();
RcppExport SEXP sigpatsearch_lib_new_search_e() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(lib_new_search_e());
    return rcpp_result_gen;
END_RCPP
}
// lib_new_search_chi
SEXP lib_new_search_chi();
RcppExport SEXP sigpatsearch_lib_new_search_chi() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(lib_new_search_chi());
    return rcpp_result_gen;
END_RCPP
}
// lib_new_search_wy_e
SEXP lib_new_search_wy_e();
RcppExport SEXP sigpatsearch_lib_new_search_wy_e() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(lib_new_search_wy_e());
    return rcpp_result_gen;
END_RCPP
}
// lib_new_search_wy_chi
SEXP lib_new_search_wy_chi();
RcppExport SEXP sigpatsearch_lib_new_search_wy_chi() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(lib_new_search_wy_chi());
    return rcpp_result_gen;
END_RCPP
}
// lib_new_search_fastcmh
SEXP lib_new_search_fastcmh();
RcppExport SEXP sigpatsearch_lib_new_search_fastcmh() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(lib_new_search_fastcmh());
    return rcpp_result_gen;
END_RCPP
}
// lib_new_search_facs
SEXP lib_new_search_facs();
RcppExport SEXP sigpatsearch_lib_new_search_facs() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(lib_new_search_facs());
    return rcpp_result_gen;
END_RCPP
}
// lib_delete_search_e
void lib_delete_search_e(SEXP inst);
RcppExport SEXP sigpatsearch_lib_delete_search_e(SEXP instSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    lib_delete_search_e(inst);
    return R_NilValue;
END_RCPP
}
// lib_delete_search_chi
void lib_delete_search_chi(SEXP inst);
RcppExport SEXP sigpatsearch_lib_delete_search_chi(SEXP instSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    lib_delete_search_chi(inst);
    return R_NilValue;
END_RCPP
}
// lib_delete_search_wy_e
void lib_delete_search_wy_e(SEXP inst);
RcppExport SEXP sigpatsearch_lib_delete_search_wy_e(SEXP instSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    lib_delete_search_wy_e(inst);
    return R_NilValue;
END_RCPP
}
// lib_delete_search_wy_chi
void lib_delete_search_wy_chi(SEXP inst);
RcppExport SEXP sigpatsearch_lib_delete_search_wy_chi(SEXP instSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    lib_delete_search_wy_chi(inst);
    return R_NilValue;
END_RCPP
}
// lib_delete_search_fastcmh
void lib_delete_search_fastcmh(SEXP inst);
RcppExport SEXP sigpatsearch_lib_delete_search_fastcmh(SEXP instSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    lib_delete_search_fastcmh(inst);
    return R_NilValue;
END_RCPP
}
// lib_delete_search_facs
void lib_delete_search_facs(SEXP inst);
RcppExport SEXP sigpatsearch_lib_delete_search_facs(SEXP instSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    lib_delete_search_facs(inst);
    return R_NilValue;
END_RCPP
}
// lib_read_eth_files
void lib_read_eth_files(SEXP inst, std::string x_filename, std::string y_filename);
RcppExport SEXP sigpatsearch_lib_read_eth_files(SEXP instSEXP, SEXP x_filenameSEXP, SEXP y_filenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    Rcpp::traits::input_parameter< std::string >::type x_filename(x_filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type y_filename(y_filenameSEXP);
    lib_read_eth_files(inst, x_filename, y_filename);
    return R_NilValue;
END_RCPP
}
// lib_read_eth_files_with_cov_fastcmh
void lib_read_eth_files_with_cov_fastcmh(SEXP inst, std::string x_filename, std::string y_filename, std::string covfilename);
RcppExport SEXP sigpatsearch_lib_read_eth_files_with_cov_fastcmh(SEXP instSEXP, SEXP x_filenameSEXP, SEXP y_filenameSEXP, SEXP covfilenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    Rcpp::traits::input_parameter< std::string >::type x_filename(x_filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type y_filename(y_filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type covfilename(covfilenameSEXP);
    lib_read_eth_files_with_cov_fastcmh(inst, x_filename, y_filename, covfilename);
    return R_NilValue;
END_RCPP
}
// lib_read_eth_files_with_cov_facs
void lib_read_eth_files_with_cov_facs(SEXP inst, std::string x_filename, std::string y_filename, std::string covfilename);
RcppExport SEXP sigpatsearch_lib_read_eth_files_with_cov_facs(SEXP instSEXP, SEXP x_filenameSEXP, SEXP y_filenameSEXP, SEXP covfilenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    Rcpp::traits::input_parameter< std::string >::type x_filename(x_filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type y_filename(y_filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type covfilename(covfilenameSEXP);
    lib_read_eth_files_with_cov_facs(inst, x_filename, y_filename, covfilename);
    return R_NilValue;
END_RCPP
}
// lib_read_plink_files
void lib_read_plink_files(SEXP inst, std::string base_filename);
RcppExport SEXP sigpatsearch_lib_read_plink_files(SEXP instSEXP, SEXP base_filenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    Rcpp::traits::input_parameter< std::string >::type base_filename(base_filenameSEXP);
    lib_read_plink_files(inst, base_filename);
    return R_NilValue;
END_RCPP
}
// lib_read_plink_files_with_cov_fastcmh
void lib_read_plink_files_with_cov_fastcmh(SEXP inst, std::string base_filename, std::string covfilename);
RcppExport SEXP sigpatsearch_lib_read_plink_files_with_cov_fastcmh(SEXP instSEXP, SEXP base_filenameSEXP, SEXP covfilenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    Rcpp::traits::input_parameter< std::string >::type base_filename(base_filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type covfilename(covfilenameSEXP);
    lib_read_plink_files_with_cov_fastcmh(inst, base_filename, covfilename);
    return R_NilValue;
END_RCPP
}
// lib_read_plink_files_with_cov_facs
void lib_read_plink_files_with_cov_facs(SEXP inst, std::string base_filename, std::string covfilename);
RcppExport SEXP sigpatsearch_lib_read_plink_files_with_cov_facs(SEXP instSEXP, SEXP base_filenameSEXP, SEXP covfilenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    Rcpp::traits::input_parameter< std::string >::type base_filename(base_filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type covfilename(covfilenameSEXP);
    lib_read_plink_files_with_cov_facs(inst, base_filename, covfilename);
    return R_NilValue;
END_RCPP
}
// lib_read_covariates_file_fastcmh
void lib_read_covariates_file_fastcmh(SEXP inst, std::string cov_filename);
RcppExport SEXP sigpatsearch_lib_read_covariates_file_fastcmh(SEXP instSEXP, SEXP cov_filenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    Rcpp::traits::input_parameter< std::string >::type cov_filename(cov_filenameSEXP);
    lib_read_covariates_file_fastcmh(inst, cov_filename);
    return R_NilValue;
END_RCPP
}
// lib_read_covariates_file_facs
void lib_read_covariates_file_facs(SEXP inst, std::string cov_filename);
RcppExport SEXP sigpatsearch_lib_read_covariates_file_facs(SEXP instSEXP, SEXP cov_filenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    Rcpp::traits::input_parameter< std::string >::type cov_filename(cov_filenameSEXP);
    lib_read_covariates_file_facs(inst, cov_filename);
    return R_NilValue;
END_RCPP
}
// lib_write_eth_files_iset
void lib_write_eth_files_iset(SEXP inst, std::string x_filename, std::string y_filename);
RcppExport SEXP sigpatsearch_lib_write_eth_files_iset(SEXP instSEXP, SEXP x_filenameSEXP, SEXP y_filenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    Rcpp::traits::input_parameter< std::string >::type x_filename(x_filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type y_filename(y_filenameSEXP);
    lib_write_eth_files_iset(inst, x_filename, y_filename);
    return R_NilValue;
END_RCPP
}
// lib_write_eth_files_int
void lib_write_eth_files_int(SEXP inst, std::string x_filename, std::string y_filename);
RcppExport SEXP sigpatsearch_lib_write_eth_files_int(SEXP instSEXP, SEXP x_filenameSEXP, SEXP y_filenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    Rcpp::traits::input_parameter< std::string >::type x_filename(x_filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type y_filename(y_filenameSEXP);
    lib_write_eth_files_int(inst, x_filename, y_filename);
    return R_NilValue;
END_RCPP
}
// lib_write_eth_files_with_cov_fastcmh
void lib_write_eth_files_with_cov_fastcmh(SEXP inst, std::string x_filename, std::string y_filename, std::string covfilename);
RcppExport SEXP sigpatsearch_lib_write_eth_files_with_cov_fastcmh(SEXP instSEXP, SEXP x_filenameSEXP, SEXP y_filenameSEXP, SEXP covfilenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    Rcpp::traits::input_parameter< std::string >::type x_filename(x_filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type y_filename(y_filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type covfilename(covfilenameSEXP);
    lib_write_eth_files_with_cov_fastcmh(inst, x_filename, y_filename, covfilename);
    return R_NilValue;
END_RCPP
}
// lib_write_eth_files_with_cov_facs
void lib_write_eth_files_with_cov_facs(SEXP inst, std::string x_filename, std::string y_filename, std::string covfilename);
RcppExport SEXP sigpatsearch_lib_write_eth_files_with_cov_facs(SEXP instSEXP, SEXP x_filenameSEXP, SEXP y_filenameSEXP, SEXP covfilenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    Rcpp::traits::input_parameter< std::string >::type x_filename(x_filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type y_filename(y_filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type covfilename(covfilenameSEXP);
    lib_write_eth_files_with_cov_facs(inst, x_filename, y_filename, covfilename);
    return R_NilValue;
END_RCPP
}
// lib_execute_iset
void lib_execute_iset(SEXP inst, double alpha, longint l_max);
RcppExport SEXP sigpatsearch_lib_execute_iset(SEXP instSEXP, SEXP alphaSEXP, SEXP l_maxSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< longint >::type l_max(l_maxSEXP);
    lib_execute_iset(inst, alpha, l_max);
    return R_NilValue;
END_RCPP
}
// lib_execute_int
void lib_execute_int(SEXP inst, double alpha, longint l_max);
RcppExport SEXP sigpatsearch_lib_execute_int(SEXP instSEXP, SEXP alphaSEXP, SEXP l_maxSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< longint >::type l_max(l_maxSEXP);
    lib_execute_int(inst, alpha, l_max);
    return R_NilValue;
END_RCPP
}
// lib_summary_write_to_file_fais
void lib_summary_write_to_file_fais(SEXP inst, std::string output_file);
RcppExport SEXP sigpatsearch_lib_summary_write_to_file_fais(SEXP instSEXP, SEXP output_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    Rcpp::traits::input_parameter< std::string >::type output_file(output_fileSEXP);
    lib_summary_write_to_file_fais(inst, output_file);
    return R_NilValue;
END_RCPP
}
// lib_summary_write_to_file_wy
void lib_summary_write_to_file_wy(SEXP inst, std::string output_file);
RcppExport SEXP sigpatsearch_lib_summary_write_to_file_wy(SEXP instSEXP, SEXP output_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    Rcpp::traits::input_parameter< std::string >::type output_file(output_fileSEXP);
    lib_summary_write_to_file_wy(inst, output_file);
    return R_NilValue;
END_RCPP
}
// lib_summary_write_to_file_fastcmh
void lib_summary_write_to_file_fastcmh(SEXP inst, std::string output_file);
RcppExport SEXP sigpatsearch_lib_summary_write_to_file_fastcmh(SEXP instSEXP, SEXP output_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    Rcpp::traits::input_parameter< std::string >::type output_file(output_fileSEXP);
    lib_summary_write_to_file_fastcmh(inst, output_file);
    return R_NilValue;
END_RCPP
}
// lib_summary_write_to_file_facs
void lib_summary_write_to_file_facs(SEXP inst, std::string output_file);
RcppExport SEXP sigpatsearch_lib_summary_write_to_file_facs(SEXP instSEXP, SEXP output_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    Rcpp::traits::input_parameter< std::string >::type output_file(output_fileSEXP);
    lib_summary_write_to_file_facs(inst, output_file);
    return R_NilValue;
END_RCPP
}
// lib_profiler_write_to_file
void lib_profiler_write_to_file(SEXP inst, std::string output_file);
RcppExport SEXP sigpatsearch_lib_profiler_write_to_file(SEXP instSEXP, SEXP output_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    Rcpp::traits::input_parameter< std::string >::type output_file(output_fileSEXP);
    lib_profiler_write_to_file(inst, output_file);
    return R_NilValue;
END_RCPP
}
// lib_filter_intervals_write_to_file
void lib_filter_intervals_write_to_file(SEXP inst, std::string output_file);
RcppExport SEXP sigpatsearch_lib_filter_intervals_write_to_file(SEXP instSEXP, SEXP output_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    Rcpp::traits::input_parameter< std::string >::type output_file(output_fileSEXP);
    lib_filter_intervals_write_to_file(inst, output_file);
    return R_NilValue;
END_RCPP
}
// lib_pvals_testable_ints_write_to_file
void lib_pvals_testable_ints_write_to_file(SEXP inst, std::string output_file);
RcppExport SEXP sigpatsearch_lib_pvals_testable_ints_write_to_file(SEXP instSEXP, SEXP output_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    Rcpp::traits::input_parameter< std::string >::type output_file(output_fileSEXP);
    lib_pvals_testable_ints_write_to_file(inst, output_file);
    return R_NilValue;
END_RCPP
}
// lib_pvals_significant_ints_write_to_file
void lib_pvals_significant_ints_write_to_file(SEXP inst, std::string output_file);
RcppExport SEXP sigpatsearch_lib_pvals_significant_ints_write_to_file(SEXP instSEXP, SEXP output_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    Rcpp::traits::input_parameter< std::string >::type output_file(output_fileSEXP);
    lib_pvals_significant_ints_write_to_file(inst, output_file);
    return R_NilValue;
END_RCPP
}
// lib_pvals_testable_isets_write_to_file
void lib_pvals_testable_isets_write_to_file(SEXP inst, std::string output_file);
RcppExport SEXP sigpatsearch_lib_pvals_testable_isets_write_to_file(SEXP instSEXP, SEXP output_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    Rcpp::traits::input_parameter< std::string >::type output_file(output_fileSEXP);
    lib_pvals_testable_isets_write_to_file(inst, output_file);
    return R_NilValue;
END_RCPP
}
// lib_pvals_significant_isets_write_to_file
void lib_pvals_significant_isets_write_to_file(SEXP inst, std::string output_file);
RcppExport SEXP sigpatsearch_lib_pvals_significant_isets_write_to_file(SEXP instSEXP, SEXP output_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    Rcpp::traits::input_parameter< std::string >::type output_file(output_fileSEXP);
    lib_pvals_significant_isets_write_to_file(inst, output_file);
    return R_NilValue;
END_RCPP
}
// lib_get_significant_intervals
SEXP lib_get_significant_intervals(SEXP inst);
RcppExport SEXP sigpatsearch_lib_get_significant_intervals(SEXP instSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    rcpp_result_gen = Rcpp::wrap(lib_get_significant_intervals(inst));
    return rcpp_result_gen;
END_RCPP
}
// lib_get_filtered_intervals
SEXP lib_get_filtered_intervals(SEXP inst);
RcppExport SEXP sigpatsearch_lib_get_filtered_intervals(SEXP instSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    rcpp_result_gen = Rcpp::wrap(lib_get_filtered_intervals(inst));
    return rcpp_result_gen;
END_RCPP
}
// lib_get_significant_itemsets
SEXP lib_get_significant_itemsets(SEXP inst);
RcppExport SEXP sigpatsearch_lib_get_significant_itemsets(SEXP instSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    rcpp_result_gen = Rcpp::wrap(lib_get_significant_itemsets(inst));
    return rcpp_result_gen;
END_RCPP
}
// lib_get_n_perm_wy
longint lib_get_n_perm_wy(SEXP inst);
RcppExport SEXP sigpatsearch_lib_get_n_perm_wy(SEXP instSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    rcpp_result_gen = Rcpp::wrap(lib_get_n_perm_wy(inst));
    return rcpp_result_gen;
END_RCPP
}
// lib_set_n_perm_wy
void lib_set_n_perm_wy(SEXP inst, longint n_perm);
RcppExport SEXP sigpatsearch_lib_set_n_perm_wy(SEXP instSEXP, SEXP n_permSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    Rcpp::traits::input_parameter< longint >::type n_perm(n_permSEXP);
    lib_set_n_perm_wy(inst, n_perm);
    return R_NilValue;
END_RCPP
}
// lib_set_perm_file_name_wy
void lib_set_perm_file_name_wy(SEXP inst, std::string filename);
RcppExport SEXP sigpatsearch_lib_set_perm_file_name_wy(SEXP instSEXP, SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    lib_set_perm_file_name_wy(inst, filename);
    return R_NilValue;
END_RCPP
}
// lib_set_seed_wy
void lib_set_seed_wy(SEXP inst, unsigned s);
RcppExport SEXP sigpatsearch_lib_set_seed_wy(SEXP instSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    Rcpp::traits::input_parameter< unsigned >::type s(sSEXP);
    lib_set_seed_wy(inst, s);
    return R_NilValue;
END_RCPP
}
// lib_get_result_fais
SEXP lib_get_result_fais(SEXP inst);
RcppExport SEXP sigpatsearch_lib_get_result_fais(SEXP instSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    rcpp_result_gen = Rcpp::wrap(lib_get_result_fais(inst));
    return rcpp_result_gen;
END_RCPP
}
// lib_get_result_int
SEXP lib_get_result_int(SEXP inst);
RcppExport SEXP sigpatsearch_lib_get_result_int(SEXP instSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    rcpp_result_gen = Rcpp::wrap(lib_get_result_int(inst));
    return rcpp_result_gen;
END_RCPP
}
// lib_get_result_iset
SEXP lib_get_result_iset(SEXP inst);
RcppExport SEXP sigpatsearch_lib_get_result_iset(SEXP instSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    rcpp_result_gen = Rcpp::wrap(lib_get_result_iset(inst));
    return rcpp_result_gen;
END_RCPP
}
// lib_get_result_facs
SEXP lib_get_result_facs(SEXP inst);
RcppExport SEXP sigpatsearch_lib_get_result_facs(SEXP instSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inst(instSEXP);
    rcpp_result_gen = Rcpp::wrap(lib_get_result_facs(inst));
    return rcpp_result_gen;
END_RCPP
}
