# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lib_new_search_e <- function() {
    .Call('_sigpatsearch_lib_new_search_e', PACKAGE = 'sigpatsearch')
}

lib_new_search_chi <- function() {
    .Call('_sigpatsearch_lib_new_search_chi', PACKAGE = 'sigpatsearch')
}

lib_new_search_fastcmh <- function() {
    .Call('_sigpatsearch_lib_new_search_fastcmh', PACKAGE = 'sigpatsearch')
}

lib_new_search_facs <- function() {
    .Call('_sigpatsearch_lib_new_search_facs', PACKAGE = 'sigpatsearch')
}

lib_delete_search_e <- function(inst) {
    invisible(.Call('_sigpatsearch_lib_delete_search_e', PACKAGE = 'sigpatsearch', inst))
}

lib_delete_search_chi <- function(inst) {
    invisible(.Call('_sigpatsearch_lib_delete_search_chi', PACKAGE = 'sigpatsearch', inst))
}

lib_delete_search_fastcmh <- function(inst) {
    invisible(.Call('_sigpatsearch_lib_delete_search_fastcmh', PACKAGE = 'sigpatsearch', inst))
}

lib_delete_search_facs <- function(inst) {
    invisible(.Call('_sigpatsearch_lib_delete_search_facs', PACKAGE = 'sigpatsearch', inst))
}

lib_read_eth_files <- function(inst, x_filename, y_filename, encoding) {
    invisible(.Call('_sigpatsearch_lib_read_eth_files', PACKAGE = 'sigpatsearch', inst, x_filename, y_filename, encoding))
}

lib_read_eth_files_with_cov_fastcmh <- function(inst, x_filename, y_filename, covfilename, encoding) {
    invisible(.Call('_sigpatsearch_lib_read_eth_files_with_cov_fastcmh', PACKAGE = 'sigpatsearch', inst, x_filename, y_filename, covfilename, encoding))
}

lib_read_eth_files_with_cov_facs <- function(inst, x_filename, y_filename, covfilename, encoding) {
    invisible(.Call('_sigpatsearch_lib_read_eth_files_with_cov_facs', PACKAGE = 'sigpatsearch', inst, x_filename, y_filename, covfilename, encoding))
}

lib_read_plink_files <- function(inst, base_filename, encoding) {
    invisible(.Call('_sigpatsearch_lib_read_plink_files', PACKAGE = 'sigpatsearch', inst, base_filename, encoding))
}

lib_read_plink_files_with_cov_fastcmh <- function(inst, base_filename, covfilename, encoding) {
    invisible(.Call('_sigpatsearch_lib_read_plink_files_with_cov_fastcmh', PACKAGE = 'sigpatsearch', inst, base_filename, covfilename, encoding))
}

lib_read_plink_files_with_cov_facs <- function(inst, base_filename, covfilename, encoding) {
    invisible(.Call('_sigpatsearch_lib_read_plink_files_with_cov_facs', PACKAGE = 'sigpatsearch', inst, base_filename, covfilename, encoding))
}

lib_read_covariates_file_fastcmh <- function(inst, cov_filename) {
    invisible(.Call('_sigpatsearch_lib_read_covariates_file_fastcmh', PACKAGE = 'sigpatsearch', inst, cov_filename))
}

lib_read_covariates_file_facs <- function(inst, cov_filename) {
    invisible(.Call('_sigpatsearch_lib_read_covariates_file_facs', PACKAGE = 'sigpatsearch', inst, cov_filename))
}

lib_write_eth_files_iset <- function(inst, x_filename, y_filename) {
    invisible(.Call('_sigpatsearch_lib_write_eth_files_iset', PACKAGE = 'sigpatsearch', inst, x_filename, y_filename))
}

lib_write_eth_files_int <- function(inst, x_filename, y_filename) {
    invisible(.Call('_sigpatsearch_lib_write_eth_files_int', PACKAGE = 'sigpatsearch', inst, x_filename, y_filename))
}

lib_write_eth_files_with_cov_fastcmh <- function(inst, x_filename, y_filename, covfilename) {
    invisible(.Call('_sigpatsearch_lib_write_eth_files_with_cov_fastcmh', PACKAGE = 'sigpatsearch', inst, x_filename, y_filename, covfilename))
}

lib_write_eth_files_with_cov_facs <- function(inst, x_filename, y_filename, covfilename) {
    invisible(.Call('_sigpatsearch_lib_write_eth_files_with_cov_facs', PACKAGE = 'sigpatsearch', inst, x_filename, y_filename, covfilename))
}

lib_execute_iset <- function(inst, alpha, l_max) {
    invisible(.Call('_sigpatsearch_lib_execute_iset', PACKAGE = 'sigpatsearch', inst, alpha, l_max))
}

lib_execute_int <- function(inst, alpha, l_max) {
    invisible(.Call('_sigpatsearch_lib_execute_int', PACKAGE = 'sigpatsearch', inst, alpha, l_max))
}

lib_summary_write_to_file_fais <- function(inst, output_file) {
    invisible(.Call('_sigpatsearch_lib_summary_write_to_file_fais', PACKAGE = 'sigpatsearch', inst, output_file))
}

lib_summary_write_to_file_fastcmh <- function(inst, output_file) {
    invisible(.Call('_sigpatsearch_lib_summary_write_to_file_fastcmh', PACKAGE = 'sigpatsearch', inst, output_file))
}

lib_summary_write_to_file_facs <- function(inst, output_file) {
    invisible(.Call('_sigpatsearch_lib_summary_write_to_file_facs', PACKAGE = 'sigpatsearch', inst, output_file))
}

lib_profiler_write_to_file <- function(inst, output_file) {
    invisible(.Call('_sigpatsearch_lib_profiler_write_to_file', PACKAGE = 'sigpatsearch', inst, output_file))
}

lib_filter_intervals_write_to_file <- function(inst, output_file) {
    invisible(.Call('_sigpatsearch_lib_filter_intervals_write_to_file', PACKAGE = 'sigpatsearch', inst, output_file))
}

lib_pvals_testable_ints_write_to_file <- function(inst, output_file) {
    invisible(.Call('_sigpatsearch_lib_pvals_testable_ints_write_to_file', PACKAGE = 'sigpatsearch', inst, output_file))
}

lib_pvals_significant_ints_write_to_file <- function(inst, output_file) {
    invisible(.Call('_sigpatsearch_lib_pvals_significant_ints_write_to_file', PACKAGE = 'sigpatsearch', inst, output_file))
}

lib_pvals_testable_isets_write_to_file <- function(inst, output_file) {
    invisible(.Call('_sigpatsearch_lib_pvals_testable_isets_write_to_file', PACKAGE = 'sigpatsearch', inst, output_file))
}

lib_pvals_significant_isets_write_to_file <- function(inst, output_file) {
    invisible(.Call('_sigpatsearch_lib_pvals_significant_isets_write_to_file', PACKAGE = 'sigpatsearch', inst, output_file))
}

lib_get_significant_intervals <- function(inst) {
    .Call('_sigpatsearch_lib_get_significant_intervals', PACKAGE = 'sigpatsearch', inst)
}

lib_get_filtered_intervals <- function(inst) {
    .Call('_sigpatsearch_lib_get_filtered_intervals', PACKAGE = 'sigpatsearch', inst)
}

lib_get_significant_itemsets <- function(inst) {
    .Call('_sigpatsearch_lib_get_significant_itemsets', PACKAGE = 'sigpatsearch', inst)
}

lib_get_result_fais <- function(inst) {
    .Call('_sigpatsearch_lib_get_result_fais', PACKAGE = 'sigpatsearch', inst)
}

lib_get_result_int <- function(inst) {
    .Call('_sigpatsearch_lib_get_result_int', PACKAGE = 'sigpatsearch', inst)
}

lib_get_result_iset <- function(inst) {
    .Call('_sigpatsearch_lib_get_result_iset', PACKAGE = 'sigpatsearch', inst)
}

lib_get_result_facs <- function(inst) {
    .Call('_sigpatsearch_lib_get_result_facs', PACKAGE = 'sigpatsearch', inst)
}

